#!/bin/sh

if [ -f ./MANIFEST.NOXSUB ]
then
	echo "Converting source from XSUB --> NOXSUB"
	mv -f MANIFEST MANIFEST.XSUB
	mv -f MANIFEST.NOXSUB MANIFEST
	mv -f Dumper.pm Dumper.pm.XSUB
	mv -f Dumper.xs Dumper.xs.XSUB
	mv -f Dumper.pm.NOXSUB Dumper.pm
else
	echo "Converting source from NOXSUB --> XSUB"
	mv -f MANIFEST MANIFEST.NOXSUB
	mv -f MANIFEST.XSUB MANIFEST
	mv -f Dumper.pm Dumper.pm.NOXSUB
	mv -f Dumper.xs.XSUB Dumper.xs
	mv -f Dumper.pm.XSUB Dumper.pm
fi